### ISSUE TITLE
Implement the `/author` endpoint

### ISSUE THREAD

**Issue by felipet** [felipet/lacoctelera_backend#27]
Implement the logic for the `/author` endpoint.

### Subtasks

- [x] Include a new DB migration to update the DB schema with all the tables needed for the author handling. 
- [ ] Define all the methods supported by the endpoint.
- [ ] Add integration tests for the methods.
- [ ] Update the API docs.
